name: liferay-auto-upgrade
run-name: Liferay Auto Upgrade

on:
  schedule:
    # https://crontab.guru/every-monday
    - cron: '0 0 * * MON'

permissions:
  contents: write
  pull-requests: write

jobs:
  liferay-upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lgdd/liferay-upgrade-action@v2
        with:
          java-distribution: 'zulu'
          java-version: '11'
